# Generated by Django 5.2.11 on 2026-02-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barber_service_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'date', 'time')},
        ),
    ]
