# Generated by Django 5.2.11 on 2026-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Paid Online'), ('shop', 'Pay in Shop')], default='shop', max_length=10),
        ),
    ]
