# Generated by Django 5.2.11 on 2026-03-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_review_notified_pushsubscription_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(blank=True, default='', max_length=30)),
                ('client_email', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='core.barber')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
