# Generated by Django 5.2.11 on 2026-03-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_barberclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
